<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="0" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-24T15:18:37 IST" name="Default suite" finished-at="2022-06-24T15:20:55 IST" duration-ms="137125">
    <groups>
      <group name="SmokeTest">
        <method signature="CreateContactsAndVerifyTest.createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" name="createContactsAndVerifyTest" class="com.crm.vtiger.createContact.CreateContactsAndVerifyTest"/>
      </group> <!-- SmokeTest -->
    </groups>
    <test started-at="2022-06-24T15:18:37 IST" name="Default test" finished-at="2022-06-24T15:20:55 IST" duration-ms="137125">
      <class name="com.crm.vtiger.createContact.CreateContactsAndVerifyTest">
        <test-method is-config="true" signature="connectToDataBase()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:18:37 IST" name="connectToDataBase" finished-at="2022-06-24T15:18:37 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectToDataBase -->
        <test-method is-config="true" signature="launchThebrowser()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:18:38 IST" name="launchThebrowser" finished-at="2022-06-24T15:18:46 IST" duration-ms="7671" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchThebrowser -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:18:46 IST" name="loginToApplication" finished-at="2022-06-24T15:18:52 IST" duration-ms="6048" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:18:52 IST" name="createContactsAndVerifyTest" finished-at="2022-06-24T15:19:07 IST" duration-ms="15310" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.vtiger.createContact.CreateContactsAndVerifyTest.createContactsAndVerifyTest(CreateContactsAndVerifyTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactsAndVerifyTest -->
        <test-method is-config="true" signature="signOutTheApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:07 IST" name="signOutTheApplication" finished-at="2022-06-24T15:19:12 IST" duration-ms="5188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTheApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:12 IST" name="loginToApplication" finished-at="2022-06-24T15:19:20 IST" duration-ms="8042" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:20 IST" name="createContactsAndVerifyTest" finished-at="2022-06-24T15:19:37 IST" duration-ms="16458" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.vtiger.createContact.CreateContactsAndVerifyTest.createContactsAndVerifyTest(CreateContactsAndVerifyTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactsAndVerifyTest -->
        <test-method is-config="true" signature="signOutTheApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:37 IST" name="signOutTheApplication" finished-at="2022-06-24T15:19:42 IST" duration-ms="4830" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTheApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:42 IST" name="loginToApplication" finished-at="2022-06-24T15:19:47 IST" duration-ms="5627" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:19:47 IST" name="createContactsAndVerifyTest" finished-at="2022-06-24T15:20:02 IST" duration-ms="14827" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.vtiger.createContact.CreateContactsAndVerifyTest.createContactsAndVerifyTest(CreateContactsAndVerifyTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactsAndVerifyTest -->
        <test-method is-config="true" signature="signOutTheApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:02 IST" name="signOutTheApplication" finished-at="2022-06-24T15:20:07 IST" duration-ms="4366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTheApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:07 IST" name="loginToApplication" finished-at="2022-06-24T15:20:12 IST" duration-ms="5026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:12 IST" name="createContactsAndVerifyTest" finished-at="2022-06-24T15:20:26 IST" duration-ms="14034" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.vtiger.createContact.CreateContactsAndVerifyTest.createContactsAndVerifyTest(CreateContactsAndVerifyTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactsAndVerifyTest -->
        <test-method is-config="true" signature="signOutTheApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:26 IST" name="signOutTheApplication" finished-at="2022-06-24T15:20:31 IST" duration-ms="5097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTheApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:31 IST" name="loginToApplication" finished-at="2022-06-24T15:20:35 IST" duration-ms="4394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method signature="createContactsAndVerifyTest()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:35 IST" name="createContactsAndVerifyTest" finished-at="2022-06-24T15:20:49 IST" duration-ms="14160" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.vtiger.createContact.CreateContactsAndVerifyTest.createContactsAndVerifyTest(CreateContactsAndVerifyTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactsAndVerifyTest -->
        <test-method is-config="true" signature="signOutTheApplication()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:50 IST" name="signOutTheApplication" finished-at="2022-06-24T15:20:54 IST" duration-ms="4809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTheApplication -->
        <test-method is-config="true" signature="closeTheBrowser()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:54 IST" name="closeTheBrowser" finished-at="2022-06-24T15:20:55 IST" duration-ms="264" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTheBrowser -->
        <test-method is-config="true" signature="closeDataBaseConnection()[pri:0, instance:com.crm.vtiger.createContact.CreateContactsAndVerifyTest@434a63ab]" started-at="2022-06-24T15:20:56 IST" name="closeDataBaseConnection" finished-at="2022-06-24T15:20:56 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDataBaseConnection -->
      </class> <!-- com.crm.vtiger.createContact.CreateContactsAndVerifyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
